apiVersion: batch/v1
kind: Job
metadata:
  name: preinstall-blocker
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: wait
          image: busybox
          command: ["sh", "-c", "while true; do sleep 3600; done"]
      restartPolicy: Never
