# q1-3
---
apiVersion: v1
kind: Namespace
metadata:
    name: neptune
    
# q5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neptune-sa-v2
  namespace: neptune
---
apiVersion: v1
kind: Secret
metadata:
  name: neptune-secret-1
  namespace: neptune
  annotations:
    kubernetes.io/service-account.name: neptune-sa-v2
type: kubernetes.io/service-account-token

# q7
---
apiVersion: v1
kind: Namespace
metadata:
  name: saturn
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-happy-shop
  name: my-happy-shop
  namespace: neptune
spec:
  containers:
    - image: nginx
      name: my-happy-shop
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  
# q8  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-new-c32
  name: api-new-c32
  namespace: neptune
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: api-new-c32
  template:
    metadata:
      labels:
        app: api-new-c32
    spec:
      containers:
        - image: nginx
          name: nginx          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-new-c32
  name: api-new-c32
  namespace: neptune
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: api-new-c32
  template:
    metadata:
      labels:
        app: api-new-c32
    spec:
      containers:
        - image: nginx:wrong
          name: nginx          